# Generated by Django 3.0.5 on 2020-04-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_remove_hospitals_hcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='district',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corona.District'),
        ),
    ]
