# Generated by Django 3.0.5 on 2020-04-04 10:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_rescue'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('typeHelp', models.CharField(choices=[('Medical', 'Medical Help'), ('Food', 'Food Related Issues'), ('police', 'Police Help'), ('safety', 'Safety Issues'), ('other', 'Others')], default='Medical Help', max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
